services:
  frontend:
    image: frontend
    build:
      context: ./example-frontend
    ports:
      - 3000:3000
    container_name: frontend
  backend:
    image: backend
    build:
      context: ./example-backend
    ports:
      - 8080:80
    environment:
      - REQUEST_ORIGIN=http://localhost:3000
    container_name: backend
# docker compose -f Compose23.yaml up
