services:
  frontend:
    image: frontend
    build:
      context: ./example-frontend
    ports:
      - 3000:3000
    container_name: frontend
  redis:
    image: redis:8.2-alpine
    container_name: redis
  backend:
    image: backend
    build:
      context: ./example-backend
    ports:
      - 8080:80
    environment:
      - REQUEST_ORIGIN=http://localhost:3000
      - REDIS_HOST=redis
    container_name: backend
# docker compose -f Compose24.yaml up

# docker run --name backend --rm -p 8080:80 -e REDIS_HOST=redis://redis:6379 backend
